# Generated by Django 4.0.4 on 2022-12-12 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'db_administrador',
            },
        ),
        migrations.CreateModel(
            name='AdultoMayor',
            fields=[
                ('id_adultoMayor', models.IntegerField(primary_key=True, serialize=False)),
                ('discapacidad', models.BooleanField()),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'db_adultoMayor',
            },
        ),
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('id_bonificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('monto_bonificacion', models.IntegerField()),
            ],
            options={
                'db_table': 'db_bonificacion',
            },
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id_credencial', models.IntegerField(primary_key=True, serialize=False)),
                ('habilitado', models.CharField(max_length=1)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'db_credencial',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('descripcion', models.TextField(max_length=500)),
                ('capacidad_max', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'db_curso',
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_discapacidad', models.IntegerField(primary_key=True, serialize=False)),
                ('discapacidad', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id_instructor', models.IntegerField(primary_key=True, serialize=False)),
                ('sueldo', models.IntegerField()),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'db_instructor',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tamano', models.IntegerField()),
                ('capacidad_max', models.IntegerField()),
            ],
            options={
                'db_table': 'db_salas',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_taller', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'db_taller',
            },
        ),
        migrations.CreateModel(
            name='TipoPefil',
            fields=[
                ('id_perfil', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'db_tipoUsuario',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id_postulacion', models.IntegerField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('documentos', models.FileField(upload_to='')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'db_table': 'db_postulacion',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('monto_pago', models.IntegerField()),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
                ('bonificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bonificacion')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instructor')),
            ],
            options={
                'db_table': 'db_pago',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(max_length=55)),
                ('cantidad', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
            ],
            options={
                'db_table': 'db_materiales',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
                ('hora_inscripcion', models.TimeField(auto_now_add=True)),
                ('adulto_mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adultomayor')),
            ],
            options={
                'db_table': 'db_inscripcion',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instructor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala'),
        ),
        migrations.AddField(
            model_name='curso',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taller'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('Calificacion', models.IntegerField()),
                ('adulto_mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adultomayor')),
            ],
            options={
                'db_table': 'db_calificacion',
            },
        ),
        migrations.CreateModel(
            name='CalifFinal',
            fields=[
                ('id_calf_final', models.IntegerField(primary_key=True, serialize=False)),
                ('calificacion_final', models.IntegerField()),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calificacion')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
            ],
            options={
                'db_table': 'db_calf_final',
            },
        ),
        migrations.AddField(
            model_name='bonificacion',
            name='calf_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.califfinal'),
        ),
        migrations.CreateModel(
            name='Autentificacion',
            fields=[
                ('id_autentificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=20)),
                ('id_credencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.credencial')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'db_autentificacion',
            },
        ),
        migrations.AddField(
            model_name='adultomayor',
            name='tipo_discapacidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discapacidad'),
        ),
    ]
