# Generated by Django 4.0.4 on 2022-12-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultomayor',
            old_name='rut_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='adultomayor',
            name='discapacidad',
        ),
        migrations.AlterField(
            model_name='discapacidad',
            name='discapacidad',
            field=models.CharField(max_length=90),
        ),
    ]
