# Generated by Django 4.0.4 on 2022-12-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rut_usuario_adultomayor_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
