# Generated by Django 4.0.4 on 2022-12-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_curso_nombre_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='rut_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='rut_usuario',
            new_name='usuario',
        ),
    ]
