# Generated by Django 4.0.4 on 2022-12-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_rut_usuario_administrador_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='img',
            field=models.ImageField(null=True, upload_to='instructores'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(upload_to='cursos'),
        ),
    ]
